global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: gateway
    metrics_path: /metrics
    scheme: http

  - job_name: 'user-auth'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: auth-service
    metrics_path: /metrics
    scheme: http

  - job_name: 'rbac'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: rbac
    metrics_path: /metrics
    scheme: http

  - job_name: 'upload'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: upload
    metrics_path: /metrics
    scheme: http 

  - job_name: 'manage-documents'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: manage-documents
    metrics_path: /metrics
    scheme: http